In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [6]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

In [7]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3888888888888889

In [8]:
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

In [11]:
scores_logistic

[0.9111111111111111,
 0.9388888888888889,
 0.8944444444444445,
 0.8666666666666667,
 0.9444444444444444,
 0.9722222222222222,
 0.9777777777777777,
 0.9497206703910615,
 0.8603351955307262,
 0.9441340782122905]

In [12]:
scores_svm

[0.4388888888888889,
 0.5777777777777777,
 0.4666666666666667,
 0.3888888888888889,
 0.4722222222222222,
 0.4,
 0.5055555555555555,
 0.5754189944134078,
 0.5586592178770949,
 0.43575418994413406]

In [13]:
scores_rf

[0.9166666666666666,
 0.9555555555555556,
 0.9444444444444444,
 0.9277777777777778,
 0.95,
 0.9611111111111111,
 0.9888888888888889,
 0.9664804469273743,
 0.9217877094972067,
 0.9385474860335196]

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [16]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [17]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=5)

array([0.93055556, 0.9       , 0.96657382, 0.97214485, 0.92479109])

In [18]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)
np.average(scores1)

0.9198603351955308

In [19]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores2)

0.9449068901303537

In [20]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores3)

0.9454562383612661

In [21]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target, cv=10)
np.average(scores4)

0.951024208566108

In [25]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target, cv=10)
np.average(scores5)

0.9499255121042831